baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sam Erickson'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[params]
    description = 'Personal website of Sam Erickson'
